"""The generated credits file: every listed source and every Bible text read."""

from __future__ import annotations

import json
from pathlib import Path
from typing import List

from assist.cite.config import CiteError, Config

NAME = "CREDITS.md"
FIELDS = (("owner", "Owner"), ("credit", "Credit line"), ("license", "Licence"),
          ("permission", "Permission"), ("url", "Link"))


def path(config: Config) -> Path:
    return config.directory / NAME


def _bible(config: Config, identify: str) -> str:
    file = config.bible_path(identify)
    try:
        info = json.loads(file.read_text(encoding="utf-8")).get("info", {})
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise CiteError(f"cannot read the Bible text '{identify}': {error}") from error
    parts = [str(info.get(key, "")).strip() for key in ("name", "shortname", "year", "publisher")]
    name, short, year, publisher = parts
    title = f"{name} ({short})" if short and short != name else name
    detail = ", ".join(part for part in (year, publisher) if part)
    return f"| `{identify}` | {title or identify} | {detail} |"


def build(config: Config) -> str:
    """Text of the credits file."""
    lines: List[str] = [
        "# Credits",
        "",
        "Generated by `python3 -m assist cite credits --apply` from `configuration.json`. Not edited by hand.",
        "",
        "## Sources",
        "",
        "A sense or an example names its source by the code shown here.",
    ]
    for code, entry in config.sources.items():
        lines += ["", f"### `{code}`: {entry['name']}", "", entry["description"], ""]
        lines += [f"- {label}: {entry[key]}" for key, label in FIELDS if entry.get(key)]
    lines += [
        "",
        "## Bible texts",
        "",
        "A reference written `book.chapter.verse` names a verse of the Zolai texts. "
        "The other texts are read for comparison only.",
        "",
        "| Id | Text | Year and publisher |",
        "| --- | --- | --- |",
    ]
    bible = config.raw["bible"]
    lines += [_bible(config, identify) for identify in bible["source"] + bible["reference"]]
    return "\n".join(lines) + "\n"


def stale(config: Config) -> bool:
    """True when the credits file is missing or differs from the configuration."""
    file = path(config)
    return not file.is_file() or file.read_text(encoding="utf-8") != build(config)
