"""Generated lookup lists: every keyword and every English term with its sense keys."""

from __future__ import annotations

from typing import Dict, List

from assist.cite import markup, query
from assist.cite.config import Config
from assist.cite.markup import Row

HEADER = "# Generated by 'python3 -m assist cite index --apply'. Not edited by hand."


def _text(header: str, entries: Dict[str, List[str]]) -> str:
    lines = [HEADER, header]
    for form in sorted(entries):
        lines.append("\t".join([form] + entries[form]))
    return "\n".join(lines) + "\n"


def keyword_index(config: Config, rows: List[Row]) -> str:
    """One line per keyword form: the form, then each keyword or sense key written that way.

    The form ignores case, hyphens, spaces and apostrophes, so keywords that
    differ only in those share a line. A keyword without a described sense is
    listed by itself. Variants of the attribute v lead to the same sense keys.
    """
    entries: Dict[str, List[str]] = {}

    def add(form: str, value: str) -> None:
        listed = entries.setdefault(query.squash(form), [])
        if value not in listed:
            listed.append(value)

    variant = config.attributes["v"]
    for row in rows:
        value = markup.row_key(row) or row.keyword
        add(row.keyword, value)
        for other in markup.split_items(variant, row.values().get("v", "")):
            if other:
                add(other, value)
    for form, listed in entries.items():
        keyed = {markup.split_key(value)[0] for value in listed if markup.split_key(value)}
        entries[form] = [value for value in listed if markup.split_key(value) or value not in keyed]
    return _text("# form, then the keywords and sense keys written that way", entries)


def term_index(config: Config, rows: List[Row]) -> str:
    """One line per English term in lowercase, then the sense keys it leads to."""
    entries: Dict[str, List[str]] = {}
    term = config.attributes["w"]
    for row in rows:
        key = markup.row_key(row)
        if not key:
            continue
        for item in markup.split_items(term, row.values().get("w", "")):
            if item:
                listed = entries.setdefault(item.casefold(), [])
                if key not in listed:
                    listed.append(key)
    return _text("# English term, then the sense keys with that term", entries)


def join_index(config: Config, rows: List[Row]) -> str:
    """One line per keyword named in j, then the sense keys of the forms that join or respell it."""
    entries: Dict[str, List[str]] = {}
    joins = config.attributes["j"]
    for row in rows:
        key = markup.row_key(row)
        if not key:
            continue
        for item in markup.split_items(joins, row.values().get("j", "")):
            if item:
                listed = entries.setdefault(item, [])
                if key not in listed:
                    listed.append(key)
    return _text("# keyword, then the sense keys of the written forms that join or respell it", entries)


def build(config: Config, rows: List[Row]) -> Dict[str, str]:
    """Text of each index file by its code."""
    settings = config.raw["index"]
    return {
        settings["keyword"]: keyword_index(config, rows),
        settings["term"]: term_index(config, rows),
        settings["join"]: join_index(config, rows),
    }


def stale(config: Config, rows: List[Row]) -> List[str]:
    """Names of the index files that are missing or differ from the data."""
    result = []
    for code, text in build(config, rows).items():
        path = config.index_path(code)
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            result.append(str(path.relative_to(config.directory)))
    return result
